services:  
  angular-app:
    build: .    
    container_name: angular-app    
    expose:      
      - "80"  
  nginx:    
    image: nginx:alpine    
    container_name: angular-nginx    
    ports:      
      - "80:80"    
    volumes:      
      - ./nginx.conf:/etc/nginx/nginx.conf    
    depends_on:      
      - angular-app
