services:
  angular-app:
    build: .
    container_name: angular-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_produccion.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - identity_media:/srv/centinela/identity_media:ro
      - social_media:/srv/centinela/social_media:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - centinela-net

networks:
  centinela-net:
    external: true

volumes:
  identity_media:
    name: centinela_identity_media
    external: true
  social_media:
    name: centinela_social_media
    external: true
