events{}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # ===== BACKEND API =====
        location /api/ {
            proxy_pass http://192.168.0.109:8000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ===== SEARCH ENGINE =====
        location /api-se/ {
            proxy_pass http://192.168.0.109:8001/api-se/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ===== WEBSOCKET =====
        location /ws/ {
            proxy_pass http://192.168.0.109:8000/ws/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
